<script type="text/javascript" src="<?php echo $this->baseUrl('/public/tinymce/jscripts/tiny_mce/jquery.tinymce.js');?>"></script>
<script type="text/javascript">
	$(document).ready(function() {
		$('textarea.tinymce').tinymce({
			// Location of TinyMCE script
			script_url : "<?php echo $this->baseUrl('/public/tinymce/jscripts/tiny_mce/tiny_mce.js')?>",
			
			relative_urls :false,

			// General options
			theme : "advanced",
			plugins : "safari,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

			// Theme options
			theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
			theme_advanced_buttons2 : "cut,copy,paste,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
			theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
			theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,/*|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak*/",
			theme_advanced_toolbar_location : "top",
			theme_advanced_toolbar_align : "left",
			theme_advanced_statusbar_location : "bottom",
			theme_advanced_resizing : true,

			// Example content CSS (should be your site CSS)
			//content_css : "css/content.css",

			// Drop lists for link/image/media/template dialogs
			//template_external_list_url : "lists/template_list.js",
			//external_link_list_url : "lists/link_list.js",
			//external_image_list_url : "lists/image_list.js",
			//media_external_list_url : "lists/media_list.js",

			// Replace values for the template plugin
			template_replace_values : {
				//username : "Some User",
				//staffid : "991234"
			}
		});
	});
</script>
<!-- /TinyMCE -->
	<div id="mid-cont">
	    <form class="pure-form" action="<?php echo $this->baseUrl('/author/upload')?>" enctype="multipart/form-data" method="post" id="uploadForm">	
		<input type="hidden" name="action" id="action" value="" />	
		<input type="hidden" name = "edit" id = "edit" value="<?php echo $this->edit; ?>" />
		<input type="hidden" name="documentname" id="documentname" value="<?php if(isset($this->name)) echo $this->name; ?>" />
		<!--<input type="hidden" name = "document" id = "document" value="<?php echo $this->document; ?>" />-->
		<div class="column1 pad-adj fleft">		
			<table cellpadding="0" cellspacing="0" class="table-style">		
				<tr class="dgrey">
					<td colspan="2">Create Playbook/Process Guide</td>
				</tr>
				<tr>
					<td width="15%"><label class = "required">Name:</label></td>
					<td width="85%"><input type="text" class="w4" name = "name" id = "name" value = "<?php echo $this->name; ?>">
					<?php if(isset($this->errors['name'])) echo "<br/>".$this->errors['name'];?><div id="duplicate"></div>
					</td>
					
				</tr>
				<tr>
					<td><label class = "required">Master Template:</label></td>
					<td><?php echo $this->formSelect(
						    'folder',
						    array(
						        $this->folder
						    ),
						    array(
						        'multiple' => false,
						    ),
							array_merge(array('' => 'Templates'),Application_Model_DbTable_MasterTemplates::getTemplates())					    	
						); ?></td> 
				</tr>				
				<tr>
					<td valign = "top" ><label class = "required">Body Content:</label></td>
					<td>
						<textarea id="elm1" name="elm1" rows="15" cols="180" style="width: 100%;" class="tinymce"><?php echo stripslashes($this->content); ?></textarea>
						<?php if(isset($this->errors['elm1'])) echo "<br/>".$this->errors['elm1'];?>
						<br/>
						<div class="container">			
						<table cellpadding="0" cellspacing="0" width="100%"  style="background:#f6f6f6;">
							<tr>
								<td align="right"><label class = "required">Type:</label></td>
								<td colspan="2"><?php echo $this->formSelect(
									    'docType',
									    array(
									        0	
									    ),
									    array(
									        'multiple' => false,
									    ),
									     array(
									        '0' => 'Choose',
									     	'1' => 'Image',
									     	'2' => 'Document',
									    )				    	
									); ?>
								</td>
							</tr>
							<tr id="metaDataRow">
								<td align="right"><label class = "required">Meta Keywords:</label></td>
								<td colspan="2"><textarea id="metaData" name="metaData" rows="3" cols="50" ></textarea><br/>Enter Meta keywords separated by comma (exp. process guide, playbook). Max 15 keywords
								</td>
							</tr>
							
							<tr>
								<td width="25%" align="right"><label class = "required">Embed File:</label></td>
								<td width="40%">							
									<div id="output"></div>
									<input id="filename" type="file" name="filename" />										  
								</td>
								<td width="35%"><!-- <span class="button fright"><a href="javascript:void(0)" title="Upload" id="uploadBtn">Upload and Embed into content area</a></span>--></td>
								
							</tr>
							
							<tr>
								<td width="25%" align="right">&nbsp;</td>
								<td colspan="2"><span class="button fleft"><a href="javascript:void(0)" title="Upload" id="uploadBtn">Upload and Embed into content area</a></span>
								</td>
							</tr>							
							
						</table>						
					  </div>
					</td>
				</tr>				
				<tr>
					<td>&nbsp;</td>
					<td>
						
						<?php if($this->send == 'y' || $this->save == 'y'):?>
						
						<span class="button fleft"><a href="javascript:void(0)" title="Preview"  id="preview">Preview</a></span>
						
						<?php endif;?>
						
						<?php if($this->save == 'y'):?>
						<span class="button fleft"><a href="javascript:void(0)" title="Save" id="saveGuide">Save</a></span>
						<?php endif;?>
						<?php if($this->send == 'y'):?>
						<span class="button fleft"><a href="javascript:void(0)" title="Send to Admin for Review" id="sendGuide">Send to Admin for Review</a></span>
						<?php endif;?>
					</td>
				</tr>
			</table>
			</form>	
		</div>
	</div>
 </div>
 <!-- jQuery Form Plug in -->
 <script type="text/javascript" src="<?php echo $this->baseUrl('/public/js/jquery.form.min.js')?> "></script>



<script>

PP.playbook.init();
var edit = '<?php echo $this->edit; ?>'
if(edit == '1')
	$('#folder').attr('disabled', 'disabled');
</script>