<div id="mid-cont">
		<h3 class="fleft">REQUESTS</h3>
		<span class="button fright"><a href="/author/requests" title="Back"><span class="back">Back</span></a></span>
		<div class="column1 pad-adj fleft">		
			<table cellpadding="0" cellspacing="0" class="table-style">			
				<tr class="dgrey">
					<td width="15%">Request Name:</td>
					<td width="85%"><?php echo $this->data['name']?></td>
				</tr>
				<tr class="lgrey brd-bottom">
					<td colspan="2"><strong>Last Message</strong>:
						<table cellpadding="0" cellspacing="0" width="100%">
							<tr>
								<td width="8%">&nbsp;</td>
								<td width="10%" align="right">Message By:</td>
								<td width="82%">Admin on <?php echo $this->data['lastMessage']['CreatedOn'];?><!-- 21st Oct, 2013--></td>
							</tr>
							<tr>
								<td>&nbsp;</td>
								<td align="right">Message:</td>
								<td><?php echo $this->data['lastMessage']['Message'];?></td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td>Status:</td>
					<td><?php echo Pp_Status::getDescriptionById($this->data['Status']); ?></td>
				</tr>
				<tr>
					<td>Request By:</td>
					<td><?php echo $this->data['name']?></td>
				</tr>
				<tr>
					<td>Assigned To:</td>
					<td><?php echo $this->data['assign']?></td>
				</tr>
				<tr>
					<td>Document URL:</td>
					<td><div class="pad-adj1 pad-adj2 fleft"><a href="#"><?php echo $this->data['DocumentUrl']?></a></div>
					<span class="button fleft"><a href="edit-request.html" title="Edit"><span class="edit">Edit</span></a></span></td>
				</tr>
				<tr>
					<td>Staging URL:</td>
					<td><a href="#"><?php echo $this->data['StagingUrl']?></a></td>
				</tr>
				<tr>
					<td>Production URL:</td>
					<td><a href="#"><?php echo $this->data['ProductionUrl']?></a></td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>
						<span class="button fleft"><a href="/author/message/request/<?php echo $this->data['RequestId']?>"><span class="send-mes" title="Send Message">Send Message</span></a></span>
					</td>
				</tr>
			</table>
		</div>
	</div>