<script>
	/*$(document).ready(function() { 
		$("#search").change(function() { 
		    window.location.href = "/author/documents/search/" + $(this).val();
		});
	});	*/
	
	function loadurl(){ 
		var val  = $("#search").val();
		window.location.href = "/author/documents/search/" + val;	
	}
	</script>
	<div id="mid-cont">
		
		<span class="button fleft"><a href="/author/create-guide" title="Add New Playbook or Process Guide"><span class="no-icon">Add New Playbook or Process Guide</span></a></span>
		
		<span class="button fleft"><a href="/author/create-document" title="Upload Document File"><span class="no-icon" >Upload Document File</span></a></span>
		
		<div class="w2 fright">
		
		<?php echo $this->formSelect(
			'search',			
			array(
				$this->search
			),		 
			array('onchange' => 'return loadurl();'),
			Pp_Type::typeArray()		
		); ?>
		</div>		
		<div class="column1 pad-adj fleft">		
			<table cellpadding="0" cellspacing="0" class="table-style table-style1">
				<tr>
					<th>Document Name</th>
					<th>Type</th>
					<th>Action</th>
				</tr>
				<?php 	
				if(isset($this->rowCount) && $this->rowCount!='0')
			   {
									
				foreach($this->data as $doc):?>
				<tr>
					<td width="40%">
					<?php if($doc['Type']!= Pp_Type::Document):?>
					<a href="/author/create-guide/document/<?php echo Pp_Common_UrlHelper::enCryptId($doc['DocumentId']); ?>"><?php echo stripslashes($doc['Name'])?></a>
					<?php Else:?>
					<?php echo stripslashes($doc['Name'])?>
					<?php Endif;?>
					</td>
					<td width="27%"><?php echo Pp_Type::getDescriptionById($doc['Type']); ?></td>
					<td width="18%">
						<?php if($doc['Type'] != Pp_Type::Document):?>
						<span class="button fleft"><a href="/author/create-guide/document/<?php echo Pp_Common_UrlHelper::enCryptId($doc['DocumentId']); ?>" title="Edit"><span class="edit-req">Edit</span></a></span>						
						<span class="button fright"><a href="javascript:void(0)" onclick= "PP.playbook._delete($(this), '<?php echo Pp_Common_UrlHelper::enCryptId($doc['DocumentId']); ?>')" class = "deleteBtn" ><span class="send-mes" title="Delete">Delete</span></a></span>						
						<?php else: ?>
						<span class="button fright"><a href="/author/delete-document/document/<?php echo Pp_Common_UrlHelper::enCryptId($doc['DocumentId']);?>"><span class="send-mes" title="Delete">Delete</span></a></span>
						<?php endIf; ?>
					</td>
				</tr>
				<?php endforeach;  }else{?>	
			   <tr>
					<td colspan="4" style="text-align:center">There are no documents available</td>
					
					</tr>
					<?php } ?>					
			</table>
		</div>
		<div class="pagination">  
		<?php echo $this->paginationControl($this->data, 'Sliding', '/partials/paginator.phtml'); ?>	   
		</div>
	</div>	
	
	
	