<div id="mid-cont">
	<div class="column1 pad-adj fleft">		
		<table cellpadding="0" cellspacing="0" class="table-style">			
			<tr class="dgrey">
				<td width="15%">Request Name:</td>
				<td width="85%">Delete <?php echo $this->data['Name']?></td>
			</tr>				
			<tr>
				<td>Folder Name:</td>
				<td><?php echo $this->data['folder']; ?></td>
			</tr>
			<tr>
				<td>File Name:</td>
				<td><?php echo Pp_Common_UrlHelper::getFileName($this->data['FileName'])?></td>
			</tr>
			<tr>
				<td colspan="2">			
					<?php echo $this->form; ?>
				</td>
			</tr>
		</table>
	</div>
</div>
<script>
PP.document._delete();
</script>
