	<script>
	/*$(document).ready(function() {
		$("#search").click(function() { alert("ssss");
		    window.location.href = "/author/requests/search/" + $(this).val();
		});
	});*/
	
	function loadurl(){
		var val  = $("#search").val();
		window.location.href = "/author/requests/search/" + val;	
	}
	</script>
	
	<div id="mid-cont">
		<h3 class="fleft">REQUESTS</h3>
		<select class="w2 fright" name="search" id="search" onchange="return loadurl();">
			<option value="<?php echo Pp_Status::Me; ?>" <?php if($this->search === Pp_Status::Me) echo "selected"; ?>>Pending with me</option>
			<option value="<?php echo Pp_Status::All; ?>" <?php if($this->search === Pp_Status::All) echo "selected"; ?>>All My Requests</option>
		</select>		
		<div class="column1 pad-adj fleft">		
			<table cellpadding="0" cellspacing="0" class="table-style table-style1">
				<tr>
					<th>Request Name</th>
					<th>Assigned To</th>
					<th>Status</th>
					<th>Action</th>
				</tr>
				<?php 
				if(isset($this->rowCount) && $this->rowCount!='0')
			   {
				
				foreach($this->data as $requests):?>
				<tr>
					<td width="30%"><a href="<?php echo Pp_Common_UrlHelper::getRequestURL($requests['RequestId'])?>"><?php echo $requests['Name']?></a></td>
					<td width="30%">
					<?php 
					if(isset($requests['assign'])) 
					$patterns = array();
					$patterns[0] = '/_pg/';
					$patterns[1] = '/_1/';
					$replacements = array();
					$replacements[0] = '';
			
					echo $assign = preg_replace($patterns, $replacements, $requests['assign']);
					
					 ?></td>
					<td width="20%"><?php echo Pp_Status::getDescriptionById($requests['Status']); ?></td>
					<td width="20%">
					<?php if($requests['Status'] != Pp_Status::Closed){ ?>
						<span class="button fleft"><a href="/author/message/request/<?php echo Pp_Common_UrlHelper::enCryptId($requests['RequestId'])?>"><span class="send-mes" title="Send Message">Send Message</span></a></span>
					<?php } else{?>	&nbsp;<?php } ?>
					</td>
				</tr>
				<?php endforeach; 
			   }else{?>	
			   <tr>
					<td colspan="4" style="text-align:center">There are no pending request(s) for you</td>
					
					</tr>
					<?php } ?>				
			</table>
			
		</div>
		<div class="pagination">   
		<?php echo $this->paginationControl($this->data, 'Sliding', '/partials/paginator.phtml'); ?>	   
		</div>
	</div>	
	
	
	
	
	