<style type="text/css">
.error-block,.errors{color:yellow;}
.hideElement{display:none;}
</style>
<div id="mid-cont"> 
	<div class="blue-box pad-adj3">
		<div><img src="<?php echo $this->baseUrl("public/images/blue-curve-top.gif")?>" alt="Blue cure" title="Blue cure" /></div>
		<table cellpadding="0" cellspacing="0" class="table-style table-style2" summary="ppeditor login,Author and Admin login">
		<tr class="hideElement">
				<th scope="row">PPEditor</th>
		</tr>
			<caption style="display:none">PPEditor Login page</caption>
			<tr>
				<td>&nbsp;</td>
				<td colspan="2"><strong>P&G users <a href="https://feddev.pg.com/affwebservices/public/saml2sso?SPID=ppeditor" class="dblue" target="_blank" title="Sign In here">Sign In here</a></strong></td>
			</tr>				
			<tr>
				<td>&nbsp;</td>
				<td colspan="2"><p class="pad-adj"><strong>Non-P&G users</strong></p></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td colspan="2">
					<div style="text-align:center;color:yellow"><?php if(isset($this->errorMsg)) echo $this->errorMsg; ?></div><?php echo $this->form ?>
				</td>
			</tr>
			<!-- <tr>
				<td width="5%">&nbsp;</td>
				<td width="28%">&nbsp;</td>
				<td width="67%"><a href="#" class="white" title="Help with Sign In">Help with Sign In</a></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>New users: <a href="request-form" class="white" title="Request account">Request account</a></td>
			</tr>-->
		</table>
		<div class="fleft"><img src="<?php echo $this->baseUrl("public/images/blue-curve-bottom.gif")?>" alt="Blue cure" title="Blue cure" /></div>
	</div>
</div>

<script>

PP.login.init();

</script>