Dear <?php echo $this->AssignedTo;?>,<br><br>

The following request has been assigned to you.<br><br>

Request Details:<br><br>

Request Name: <b><?php echo $this->name ?></b> <br>
Status		:<b><?php echo $this->status ?></b>	<br>
RequestBy	:<b><?php echo $this->RequestBy ?></b>	<br>
AssignedTo	:<b><?php echo $this->AssignedTo ?></b>	<br>

DocumentUrl	:<b><a href="<?php echo $this->DocumentUrl ?>"><?php echo $this->DocumentUrl ?></a></b>	
		




