
	<div id="mid-cont">
		<h3 class="fleft">CONFIGURATION</h3>
		
		<div class="column1 pad-adj fleft">		
		<form name="configuration" id="configuration" action="/admin/configuration" method="post" />
		<input type="hidden" name="Configid" value="<?php echo $this->rs['ConfigId']; ?>" />
		
			<table cellpadding="0" cellspacing="0" class="table-style" summary="PPEditor Configuration" >		
			<caption style="display:none">PPEditor Configuration</caption>
				<tr>
					<td>Ops Specialist Name:</td>
					<td><input type="text" value="<?php if(isset($this->rs['OpsSpecialistName'])){ echo $this->rs['OpsSpecialistName']; } ?>" class="w3" name="OpsSpecialistName" id="OpsSpecialistName" /></td>
					<div class="error"></div>
				</tr>
				<tr>
					<td>Ops Specialist EmailId:</td>
					<td><input type="text" value="<?php if(isset($this->rs['OpsSpecialistEmailId'])){ echo $this->rs['OpsSpecialistEmailId']; } ?>" class="w3" name="OpsSpecialistEmailId" id="OpsSpecialistEmailId" /></td>
				</tr>
				<tr>
					<td>Tech Agency Lead Name:</td>
					<td><input type="text" value="<?php if(isset($this->rs['TechAgencyLeadName'])){ echo $this->rs['TechAgencyLeadName']; } ?>" class="w3" name="TechAgencyLeadName" id="TechAgencyLeadName" /></td>
				</tr>
				<tr>
					<td>Tech Agency Lead EmailId:</td>
					<td><input type="text" value="<?php if(isset($this->rs['TechAgencyLeadEmailId'])){ echo $this->rs['TechAgencyLeadEmailId']; } ?>" class="w3" name="TechAgencyLeadEmailId" id="TechAgencyLeadEmailId" /></td>
				</tr>
				<tr>
					<td>Tech Agency Developer Name:</td>
					<td><input type="text" value="<?php if(isset($this->rs['TechAgencyDeveloperName'])){ echo $this->rs['TechAgencyDeveloperName']; } ?>" class="w3" name="TechAgencyDeveloperName" id="TechAgencyDeveloperName" /></td>
				</tr>
				<tr>
					<td>Tech Agency Developer EmailId:</td>
					<td><input type="text" value="<?php if(isset($this->rs['TechAgencyDeveloperEmailId'])){ echo $this->rs['TechAgencyDeveloperEmailId']; } ?>" class="w3" name="TechAgencyDeveloperEmailId" id="TechAgencyDeveloperEmailId" /></td>
				</tr>
				
				<tr>
					<td>&nbsp;</td>
					<td><input type="submit" value="Save" id="submit"  class="sm-btn" />
						
					</td>
				</tr>
			</table>
		</div>
	</div>
	
<script>

PP.config.init();

</script>