	<div id="mid-cont">
		<h3 class="fleft">VIEW REQUEST</h3>
		<span class="button fright"><a href="/admin/requests/search/<?php echo $this->search?>" title="Back"><span class="back">Back to Request Listing</span></a></span>
		<div class="column1 pad-adj fleft">		
			<table cellpadding="0" cellspacing="0" class="table-style" summary="View Request">
			<caption style="display:none">View Request</caption>				
				<tr class="dgrey">
					<td width="15%">Request Name:</td>
					<td width="85%" style="font-weight:bold;color:#F5F6CE"><?php echo $this->rs['Name'];?></td>
				</tr>
				<tr class="lgrey brd-bottom">
					<td colspan="2"><strong>Last Message</strong>:
						<table cellpadding="0" cellspacing="0" width="100%">
							<tr>
								<td width="8%">&nbsp;</td>
								<td width="10%" align="right">Message By:</td>
								<td width="82%"><?php echo $this->rs['lastMessage']['MessagedBy'];?> on <?php echo $this->rs['lastMessage']['dt'];?></td>
							</tr>
							<tr>
								<td>&nbsp;</td>
								<td align="right">Message:</td>
								<td><?php echo $this->rs['lastMessage']['Message'];?></td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td>Status:</td>
					<td><?php echo Pp_Status::getDescriptionById($this->rs['Status']);?></td>
				</tr>
				<tr>
					<td>Request By:</td>
					<td><?php echo $this->rs['CreatedBy']; ?></td>
				</tr>
				<tr>
					<td>Assigned To:</td>
					<td><?php
					//echo $this->rs['assign'];
					if(isset($this->rs['AssignedTo']) && $this->rs['AssignedTo']!='NULL' && $this->rs['AssignedTo'] !='0')
					echo $assignee = (in_array($this->rs['AssignedTo'], $this->admin_id))? $this->rs['assign'] : '';			
					         				
					?></td>
				</tr>
				<?php if($this->rs['Type'] != 'd'){?>
				<tr>
					<td>Document URL:</td>
					<td><div class="pad-adj1 pad-adj2 fleft"><a href="<?php echo Pp_Common_UrlHelper::getPreviewURL($this->rs['DocumentId']); ?>" target="_blank"><?php echo Pp_Common_UrlHelper::getPreviewURL($this->rs['DocumentId']); ?></a></div>
					<?php if(Pp_Common_UrlHelper::getPreviewURL($this->rs['DocumentId'])){ ?><span class="button fleft"><a href="/admin/edit-document/document/<?php echo $this->rs['DocumentId']; ?>/request/<?php echo $this->rs['RequestId'];?>" title="Edit"><span class="edit">Edit</span></a></span><?php }?></td>
				</tr>
				<tr>
					<td>Staging URL:</td>
					<td><a href="<?php echo $this->rs['StagingUrl']; ?>"><?php echo $this->rs['StagingUrl']; ?></a></td>
				</tr>
				<tr>
					<td>Production URL:</td>
					<td><a href="<?php echo $this->rs['ProductionUrl']; ?>"><?php echo $this->rs['ProductionUrl']; ?></a></td>
				</tr>
				<?php }else{ ?>
				<tr>
					<td>Attachment:</td>
					<td><a href="<?php echo $this->docViewPath.$this->rs['FileName']; ?>"><?php echo $this->rs['FileName']; ?></a></td>
				</tr>
				
				<?php }?>
				<tr>
					<td>&nbsp;</td>
					<td><span class="button fleft"><a href="/admin/editrequest/request/<?php echo $this->rs['RequestId'] ?>/search/<?php if(isset($this->search)) echo $this->search;?>" title="Edit Request"><span class="edit-req">Edit Request</span></a></span>
						<span class="button fleft"><a href="/admin/sendmsg/request/<?php echo $this->rs['RequestId'] ?>/search/<?php if(isset($this->search)) echo $this->search;?>"><span class="send-mes" title="Send Message">Send Message</span></a></span>
						<?php if($this->rs['Type'] != 'd' && $this->rs['Status']!=Pp_Status::TA){?>
						<span class="button fleft"><a href="/admin/sendtota/request/<?php echo $this->rs['RequestId'] ?>/search/<?php if(isset($this->search)) echo $this->search;?>"><span class="send-ta" title="Send to Technical Agency">Send to Technical Agency</span></a></span>
						<?php }?>
					</td>
				</tr>
			</table>
		</div>
	</div>